name: FallOutInventoryClear
main: str0nix\foic\Main
version: 1.1.0
api: [3.0.0, 3.10.0, 3.15.0]
author: str0nix
description: This plugin clears your inventory if you fall out from the world
website: https://github.com/str0nixofficial

commands:
 foic:
  description: "FOIC Informations"
  usage: /foic
